### ISSUE TITLE
Sketch not 'seeing' changes without removing plugin and re-installing 

### ISSUE THREAD

**Issue by benfrain** [BohemianCoding/SketchAPI#193] opened 2018-05-16 16:52 UTC
When I run `npm run watch` my build is working as expected. However, Sketch is no longer seeing the changes to the local dev version (it was originally). 

At present, I have to keep uninstalling the plugin from the Plugin menu and then re-installing by clicking my `pluginName.sketchplugin` file.

Is there a particular 'flag' I need to set somewhere to get Sketch to update incremental changes when I am developing locally? Is it because I now have a `appcast` in my manifest (I did try deleting that entry to no avail)?

Any pointers appreciated.

**Comment by mathieudutour** [comment] 2018-05-16 20:13
Have a look here: https://developer.sketchapp.com/guides/preferences/#always-reload-scripts-before-running

I guess you are using skpm? It should have enabled the setting for you. But perhaps you are now using the Sketch beta and you will need to do it manually.

I'm going to close this as it's not really a bug but more a question

**Closed by mathieudutour** 2018-05-16 20:13 UTC

**Comment by robintindale** [comment] 2018-05-17 09:43
One possibility is that your script is long-running for some reason - this can either be because you're using `coscript` `shouldKeepAround`, using a `fiber`, or your program crashes in a way that doesn't cleanup the context.

If a script is long-running, the plugin won't be reloaded when you run a command again, as it will just re-use the old context. You can find out by running
```
var pm = AppController.sharedInstance().pluginManager();
var c = pm.runningCommands();
var command = c.objectEnumerator().nextObject()
log(c)
```
which will log something if your plugin is still running after you execute a command.

**Comment by benfrain** [comment] 2018-05-17 10:04
@robintindale Ah, OK, thanks. Could you just clarify, I am currently using:

```javascript
// Get choice of drop-down from user
    var choice = UI.getSelectionFromUser("Which Language?", listOfLanguages);
    var ok = choice[2];
    var value = listOfLanguages[choice[1]];

    // Once OK is clicked on the menu
    if (ok) {
//...more
```

I then add your above snippet at the end of that `if (ok)` which is logging:

```
{
    "<MSPluginCommandSpecifier: 0x608000223cc0>" = "<MSPluginCommand: 0x6000002e5c00>";
}
```

This is telling me my script is long running – is that correct?

**Comment by benfrain** [comment] 2018-05-17 11:05
Ha! Glad I asked :)

I get this:

```
{
}

Script executed in 0.016127s
```

Presume that means it isn't that? 

I suspect as a newbie, I am doing something obviously stupid as it was working at first. 

In case it helps, here is a gist containing my `src` files (I have omitted `mlStrings.js` as it is just a JS object of data) and `package.json`.

https://gist.github.com/benfrain/4914e1a4232ea6037ed20042696d0ae9

**Comment by robintindale** [comment] 2018-05-17 12:02
Yes, OK looks like it's not a long-running issue.

I just saw that you are reinstalling the plugin each time - this could be the cause, as this will just copy a static version of the files into the `Plugins` directory, so changing things in your `skpm` directory *won't* have any effect. You need to reset a symlink from `Plugins` to the `.sketchplugin` in your local `skpm` directory.

* Go to `~/Library/Application\ Support/com.bohemiancoding.sketch3/Plugins` and delete your plugin
* in your `skpm` folder, run `./node_modules/.bin/skpm-link` - this should reset the symlink

Give that a go :)

**Comment by mathieudutour** [comment] 2018-05-17 12:06
Ah yes good thinking! I’m wondering if I can check if there is a symlink when running `npm run watch` and print a warning. That’s not the first time it happened

**Comment by robintindale** [comment] 2018-05-17 14:53
yep sorry, the folder you are developing your plugin in - where the `package.json` is :)

**Comment by benfrain** [comment] 2018-05-17 15:10
OK, @robintindale said to 'run' the `skpm-link` - I take it that means from the 'Run script command'?

**Comment by robintindale** [comment] 2018-05-17 15:37
no, from a Terminal window in your plugin directory 👍

**Comment by benfrain** [comment] 2018-05-17 15:55
Sorry, not having any joy with that?

<img width="732" alt="screen shot 2018-05-17 at 16 53 31" src="https://user-images.githubusercontent.com/1318466/40188923-fc27e6f0-59f2-11e8-8e23-a601c5312496.png">

**Comment by mathieudutour** [comment] 2018-05-17 15:56
that's what you need to run:
```
cd ~/Sites/TranslateText && ./node_modules/.bin/skpm-link
```

**Comment by robintindale** [comment] 2018-05-17 16:06
And a hint for why it wasn't working - if you're trying to run a file in the current directory, you need to prefix `./`, so if you're in `~/Sites/TranslateText/node_modules/.bin`, you'd need to execute `./skpm-link`. Otherwise, it will just look in your normal `$PATH` and not find anything

**Comment by benfrain** [comment] 2018-05-17 16:40
@mathieudutour @robintindale thanks men, running great again now! Thanks for your patience 👍
